const movies = [
  {
    id: 278, // TMDB Movie ID
    title: 'Pabėgimas iš Šoušenko',
    genre: ['Drama', 'Kriminalinis'],
    rating: 8.7,
    year: 1994,
    poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/278-the-shawshank-redemption',
  },
  {
    id: 238,
    title: 'Krikštatėvis',
    genre: ['Drama', 'Kriminalinis'],
    rating: 8.7,
    year: 1972,
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/238-the-godfather',
  },
  {
    id: 155,
    title: 'Tamsos riteris',
    genre: ['Drama', 'Veiksmo', 'Kriminalinis', 'Trileris'],
    rating: 8.5,
    year: 2008,
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/155-the-dark-knight',
  },
  {
    id: 424,
    title: 'Šindlerio sąrašas',
    genre: ['Drama', 'Istorinis', 'Karinis'],
    rating: 8.6,
    year: 1993,
    poster: 'https://image.tmdb.org/t/p/w500/c8Ass7acuOe4za6DhSattE359gr.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/424-schindlers-list',
  },
  {
    id: 680,
    title: 'Bulvarinis skaitalas',
    genre: ['Drama', 'Kriminalinis'],
    rating: 8.5,
    year: 1994,
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/680-pulp-fiction',
  },
  {
    id: 122,
    title: 'Žiedų valdovas: Karaliaus sugrįžimas',
    genre: ['Nuotykių', 'Fantastinis', 'Veiksmo'],
    rating: 8.5,
    year: 2003,
    poster: 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/122-the-lord-of-the-rings-the-return-of-the-king',
  },
  {
    id: 13,
    title: 'Forestas Gampas',
    genre: ['Komedija', 'Drama', 'Romantinis'],
    rating: 8.5,
    year: 1994,
    poster: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/13-forrest-gump',
  },
  {
    id: 27205,
    title: 'Pradžia',
    genre: ['Veiksmo', 'Nuotykių', 'Mokslinė fantastika'],
    rating: 8.4,
    year: 2010,
    poster: 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/27205-inception',
  },
  {
    id: 550,
    title: 'Kovos klubas',
    genre: ['Drama', 'Trileris'],
    rating: 8.3,
    year: 1999,
    poster: 'https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/550-fight-club',
  },
  {
    id: 157336,
    title: 'Tarp žvaigždžių',
    genre: ['Nuotykių', 'Drama', 'Mokslinė fantastika'],
    rating: 8.4,
    year: 2014,
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/157336-interstellar',
  },
  {
    id: 603,
    title: 'Matrica',
    genre: ['Veiksmo', 'Mokslinė fantastika'],
    rating: 8.3,
    year: 1999,
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/603-the-matrix',
  },
  {
    id: 98,
    title: 'Gladiatorius',
    genre: ['Veiksmo', 'Nuotykių', 'Drama'],
    rating: 8.3,
    year: 2000,
    poster: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/98-gladiator',
  },
  {
    id: 68718,
    title: 'Django Unchained',
    genre: ['Drama', 'Veiksmo', 'Vakarietiškas'],
    rating: 8.3,
    year: 2012,
    poster: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg',
    detailsUrl: 'https://www.themoviedb.org/movie/68718-django-unchained',
  },
];

export default movies;
